# Name your project! Ensure it's lowercase and reflects the project's purpose.
name: 'dbt_snowflake'  # Changed to a unique project name to avoid conflicts.
version: '1.0.0'

# Specify which dbt profile to use. This should match the profile in your `profiles.yml`.
profile: 'dbt_project'

# File path configurations for dbt resources.
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

# Clean targets configuration: These directories will be removed by `dbt clean`.
clean-targets:
  - "target"
  - "dbt_packages"

# Configure seeds (CSV files loaded into the database).
seeds:
  +schema: raw  # Seeds will be loaded into the RAW schema.
  +name: seed    # Ensures the table is named SEED in the RAW schema.
  snowflake_warehouse: dbt_wh


# Configure models (dbt SQL files).
models:
    # Staging models (incremental by default, stored in the `staging` schema).
    staging:
      +materialized: incremental
      +schema: staging
      snowflake_warehouse: dbt_wh
    
    # Mart models (analytics-ready, stored in the `marts` schema as tables).
    marts:
      +materialized: table
      +schema: marts
      snowflake_warehouse: dbt_wh

# Optional configurations for snapshots (if used).
snapshots:
    +schema: snapshots
    snowflake_warehouse: dbt_wh
