# Name your project! Ensure it's lowercase and reflects the project's purpose.
name: 'my_books_project'  # Changed to a unique project name to avoid conflicts.
version: '1.0.0'

# Specify which dbt profile to use. This should match the profile in your `profiles.yml`.
profile: 'dbt_snowflake'

# File path configurations for dbt resources.
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

# Clean targets configuration: These directories will be removed by `dbt clean`.
clean-targets:
  - "target"
  - "dbt_packages"

# Configure seeds (CSV files loaded into the database).
seeds:
  +schema: raw
  amazon_books:
    +column_types:
      title: string
      rank: integer
      reviews: float
      review_count: integer
      price: float
      genre: string
      manufacturer: string
      brand: string
      author: string
      number_of_pages: integer





# Configure models (dbt SQL files).
models:
  my_books_project:  # Reflect the updated project name here.
    # Staging models (incremental by default, stored in the `staging` schema).


    staging:
      +materialized: incremental
      +schema: staging
      snowflake_warehouse: dbt_wh
    
    # Mart models (analytics-ready, stored in the `marts` schema as tables).
    marts:
      +materialized: table
      +schema: marts
      snowflake_warehouse: dbt_wh

# Optional configurations for snapshots (if used).
snapshots:
  my_books_project:  # Reflect the updated project name here.
    +schema: snapshots
    snowflake_warehouse: dbt_wh
