# Name your project! Ensure it's lowercase and reflects the project's purpose.
name: 'my_books_project'  # Changed to a unique project name to avoid conflicts.
version: '1.0.0'

# Specify which dbt profile to use. This should match the profile in your `profiles.yml`.
profile: 'dbt_snowflake'

# File path configurations for dbt resources.
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

# Clean targets configuration: These directories will be removed by `dbt clean`.
clean-targets:
  - "target"
  - "dbt_packages"


models:
  my_books_project:
    # Default settings for all models
    +materialized: view
    +schema: default

    staging:
      +materialized: view
      +schema: staging

    intermediate:
      +materialized: view
      +schema: intermediate

    marts:
      +materialized: table
      +schema: marts  # Ensures all marts models go to the marts schema
      dimensions:
        +schema: marts  # Inherit from marts
      marketing:
        +schema: marts  # Inherit from marts
      sales:
        +schema: marts  # Inherit from marts


# Optional configurations for snapshots (if used).
snapshots:
  my_books_project:  # Reflect the updated project name here.
    +schema: snapshots
    snowflake_warehouse: dbt_wh
