  streamlit:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    environment:
      STREAMLIT_SECRETS: /app/.streamlit/secrets.toml
    volumes:
      - ./app:/app
