snowflake_account = "cinckov-wu26490"
snowflake_user = "DBT_USER"
snowflake_password = "Trakinas123!"
snowflake_role = "dbt_role"
snowflake_database = "dbt_project"
snowflake_schema = "dbt_marts"
snowflake_warehouse = "dbt_wh"
snowflake_threads = 1
