version: 2

seeds:
  - name: amazon_books
    description: "Seed table for Amazon books data."
    columns:
      - name: title
        description: "Title of the book."
        tests:
          - not_null
      - name: rank
        description: "Amazon rank of the book."
      - name: reviews
        description: "Average review rating (out of 5)."
      - name: review_count
        description: "Total number of reviews."
      - name: price
        description: "Price of the book in USD."
      - name: genre
        description: "Genre or category of the book."
      - name: manufacturer
        description: "Publisher or manufacturer."
      - name: brand
        description: "Brand associated with the book, if any."
      - name: author
        description: "Author of the book."
      - name: number_of_pages
        description: "Number of pages."
